# Generated by Django 4.2.3 on 2023-08-10 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deportista',
            name='federado',
        ),
        migrations.AddField(
            model_name='deportista',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deporte',
            name='categoría',
            field=models.CharField(max_length=50),
        ),
    ]
